server {
    listen 443 ssl http2;
    server_name autoextrato.sgecont.com.br;

    ssl_certificate /etc/letsencrypt/live/autoextrato.sgecont.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/autoextrato.sgecont.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://autoextrato:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
